package com.example.demo.Service;

import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import com.example.demo.configuration.EmailDetails;
import com.example.demo.dao.EmailDao;
import com.example.demo.service.EmailService;

@ExtendWith(MockitoExtension.class)
public class EmailServiceTest {
	
	@Mock
	EmailDao emailDao;
	
	@InjectMocks
	EmailService emailService;
	
	EmailDetails emailDetails;
	
	@BeforeEach
	public void setup() {
		emailDetails = EmailDetails.builder()
				.recipient("191043107007@gperi.ac.in")
				.subject("testing email service")
				.msgBody("This is an autogenerated test email")
				.build();
	}
	
	@Test
	public void sendmail_success() throws Exception{
		
		when(emailDao.sendSimpleEmail(emailDetails)).thenReturn("Mail sent successfully....");
		
		String status = emailService.sendSimpleEmail(emailDetails);
		
		System.out.println(status);
		
	}

}
